# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ShowXYPoint
                                 A QGIS plugin
 Menampilkan titik berdasarkan input titik koordinat
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-06-05
        copyright            : (C) 2024 by Hilman Thoriq | SIG UGM 2024
        email                : hilmanthoriq@mail.ugm.ac.id
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ShowXYPoint class from file ShowXYPoint.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .show_xy_point import ShowXYPoint
    return ShowXYPoint(iface)
